name: Merge Queue
on:
  push:
    branches: [ master ]
  pull_request:
    types: [labeled, unlabeled]
  pull_request_review:
    branches: [ master ]
jobs:
  label-next-up:
    runs-on: ubuntu-latest
    steps:
      - name: Find and label automerge candidate matching the 'merge:ready' label
        uses: jakobe/automerge-labeler@master
        id: automerge_labeler
        with:
          label-candidate: 'merge:ready'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_GITHUB_TOKEN }}
      - run: "echo 'PR ready for automerge: ${{ steps.automerge_labeler.outputs.pull_request }}'"
