name: Merge Queue
on:
  push:
    branches:
      - master

jobs:
  label-next-up:
    runs-on: ubuntu-latest
    steps:
      - name: Find and label automerge candidate matching the 'merge:ready' label
        uses: jakobe/automerge-labeler@master
        id: automerge_labeler
        with:
          label-candidate: 'merge:ready'
      - run: "echo 'PR ready for automerge: ${{ steps.automerge_labeler.outputs.pull_request }}'"
